# Generated by Django 2.2.28 on 2023-06-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearStore', '0012_auto_20230531_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(default='site_images/default_background.jpg', upload_to='site_images')),
                ('logo_image', models.ImageField(default='site_images/default_logo.png', upload_to='site_images')),
                ('home_contents', models.TextField()),
                ('about_contents', models.TextField()),
                ('contact_contents', models.TextField()),
                ('contact', models.CharField(max_length=128)),
                ('contact_option', models.CharField(choices=[('<ion-icon name="logo-whatsapp"></ion-icon>', 'WhatsApp'), ('<ion-icon name="call-outline"></ion-icon>', 'Phone Number'), ('<ion-icon name="mail-outline"></ion-icon>', 'Email')], default='<ion-icon name="call-outline"></ion-icon>', max_length=128)),
            ],
        ),
    ]
