# Generated by Django 2.2.28 on 2023-03-15 14:32

from django.db import migrations, models
import guccSite.models


class Migration(migrations.Migration):

    dependencies = [
        ('guccSite', '0008_auto_20230315_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateToReturn',
            field=models.DateField(default=guccSite.models.return_date_time),
        ),
    ]
