# Generated by Django 2.2.28 on 2023-05-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guccSite', '0011_auto_20230323_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='colour',
        ),
        migrations.AlterField(
            model_name='gear',
            name='size',
            field=models.CharField(max_length=128),
        ),
    ]
