# Generated by Django 2.2.28 on 2023-06-16 10:55

from django.db import migrations, models
import guccSite.models


class Migration(migrations.Migration):

    dependencies = [
        ('guccSite', '0014_auto_20230612_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.TextField(default=guccSite.models.id_generator, max_length=6, primary_key=True, serialize=False),
        ),
    ]
