# Generated by Django 2.2.28 on 2023-06-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guccSite', '0016_auto_20230617_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guccSite.Booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guccSite.UserProfile')),
            ],
        ),
    ]
