# Generated by Django 2.2.28 on 2023-09-08 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import guccSite.models


class Migration(migrations.Migration):

    dependencies = [
        ('guccSite', '0017_bookingcomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarLinks',
            fields=[
                ('link_text', models.TextField()),
                ('url', models.URLField()),
                ('id', models.TextField(default=guccSite.models.comment_id_generator, max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.TextField(choices=[('Affiliated', 'Affiliated'), ('Personal', 'Personal')], default='Personal'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Returned', 'Returned'), ('Unreturned', 'Unreturned')], default='Requested', max_length=16),
        ),
        migrations.AddField(
            model_name='bookingcomments',
            name='dateAdded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingcomments',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gear',
            name='deposit',
            field=models.TextField(default='Yes', max_length=16),
        ),
        migrations.AddField(
            model_name='gear',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Out Of Service', 'Out Of Service')], default='In Service', max_length=16),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='domain',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='icon_image',
            field=models.ImageField(default='site_images/default_icon.png', upload_to='site_images'),
        ),
        migrations.AlterField(
            model_name='bookingcomments',
            name='id',
            field=models.TextField(default=guccSite.models.comment_id_generator, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='about_contents',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='contact',
            field=models.CharField(default='07123 456 789', max_length=128),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='contact_contents',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='home_contents',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='QR_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(default='qrcode_images/default_qrcode.png', upload_to='qrcode_images')),
                ('domain', models.TextField(default='')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guccSite.Booking')),
            ],
        ),
    ]
