# Generated by Django 2.2.28 on 2023-09-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guccSite', '0018_auto_20230908_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontents',
            name='contact_option',
            field=models.CharField(choices=[('logo-instagram', 'Instagram'), ('logo-facebook', 'Facebook'), ('mail-outline', 'Email')], default='logo-facebook', max_length=128),
        ),
    ]
