# Generated by Django 2.2.28 on 2023-09-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guccSite', '0019_auto_20230911_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontents',
            name='contact_option',
            field=models.CharField(choices=[('logo-instagram', 'Instagram'), ('logo-facebook', 'Faceook'), ('mail-outline', 'Email')], default='logo-facebook', max_length=128),
        ),
    ]
