# Generated by Django 2.2.28 on 2023-09-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guccSite', '0020_auto_20230911_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
